#!/bin/bash

set -e

if [ "$1" = "purge" ]; then
    # Remove service user and group
    if getent passwd m17-bridge >/dev/null; then
        userdel m17-bridge
    fi
    
    if getent group m17-bridge >/dev/null; then
        groupdel m17-bridge
    fi

    # Remove config
    rm -f /etc/m17-bridge.ini

    echo "M17 Messaging Bridge service and user data removed."
fi
